---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values. deployment.label }}
  replicas: 2
  template: 
    metadata:
      labels:
        app: {{ .Values. deployment.label }}
    spec:
      containers:
      - name: {{ .Values. deployment.label }}
        image: "{{ .Vvalues. deployment.image }}: {{ .Values. deployment.tag }}"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
      nodeSelector:
        disktype: ssd

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: apache-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
kind: Service
apiVersion: v1
metadata:
  name: testfrontend
spec:
  selector:
    app: apache
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
