apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - default:
      cpu: "800m"
      memory: "800Mi"
    defaultRequest:kubectl exec -nprod -it <your-dj-pod-name> -c dj bash

      cpu: "800m"
      memory: "800Mi"
    max:
      cpu: "800m"
      memory: "800Mi"
    min:
      cpu: "200m"
      memory: "200Mi"
    type: Container